spring.application.name=grievance-management

# MySQL Cloud Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://avnadmin:AVNS_6-I1ATe-IUN7rbFuo2x@mysql-31858198-avverma7620-82ac.d.aivencloud.com:27112/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AVNS_6-I1ATe-IUN7rbFuo2x}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server (Supports Cloud PORT like Render/Railway/Heroku)
server.port=${PORT:8080}

# JWT
jwt.secret=${JWT_SECRET:MyVillageGrievanceSystemSecretKeyForJWT2026Secure}
jwt.expiration=86400000